
version: '3.8'

services:
  # Приложение мониторинга
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elastic-monitor
    ports:
      - "8080:80"
    networks:
      - elastic-network


networks:
  elastic-network:
    driver: bridge
